spring:
  datasource:
    url: jdbc:mysql://api.local.static.run:3306/static_run?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: password
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          gitee:
            authorization-grant-type: authorization_code
            client-secret: a29c98da4eda02c2feb25a2c8101fd7e690de107c033dd089f95a81b6c71325e
            client-id: d2f9e18260752305f57cf4dd144d5984e50119783b4320fcae7ecebfa1f68a69
            scope:
              - user_info
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/authorized/{registrationId}"
          github:
            authorization-grant-type: authorization_code
            client-secret: f08441321811c17d20099bc94c0e6c145297a577
            client-id: 1981b592d396a2672aae
            scope:
              - read:user
logging:
  level:
    web: debug
    io:
      github:
        mitu2: debug
server:
  address: api.local.static.run