spring:
  thymeleaf:
    cache: true
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    web: info
    io:
      github:
        mitu2: info