spring:
  security:
    oauth2:
      client:
        provider:
          gitee:
            user-name-attribute: name
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
  profiles:
    active:
      - default
      - dev
  application:
    name: static-run-springboot
  sql:
    init:
      data-locations:
        - classpath:sql/*.sql
      mode: ALWAYS
      continue-on-error: true
  web:
    locale: zh_CN
  jackson:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  pid:
    fail-on-write-error: true
    file: ${system.work-dir}/application.pid
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  compression:
    enabled: true
logging:
  file:
    path: ${system.work-dir}/logs
system:
  work-dir: ${user.home}/.SpringStaticRunApplication